### ISSUE TITLE
Encodo Style Settings Files as public Nuget

### ISSUE THREAD

**Issue by mduu** [mvonballmo/CSharpHandbook#1]
Can I get the Encodo Style Settings files as a Nuget package right into my projects? Would be awesome (and upgradeable).

Cheers, Marc

**Comment by mvonballmo** [comment]
That's an interesting suggestion. I could easily provide the .dotSettings file, but I'm not sure how to put it into a Nuget package---especially since Nuget deprecated solution-level packages a while back. You can still use them, and nuget restores them when you execute from the command line, but VS ignores them.

Generally, I have one .dotSettings file at the solution root that applies to all projects. Then I have another in the "tests" folder that shuts off StyleCop's documentation requirements.

I'm not quite sure how to do that with a Nuget package (especially since they either don't allow or strongly discourage script-execution).

**Comment by mduu** [comment]
That’s all true. We did this using a install.ps that searches the sln and places the files next to it. But it’s a little hacky and one has issues with this when the files are not totally current. Then they get changed by VS and R#. After package restore they are reset. VS /R# will update (change) them again. Not cool. So maybe a nuget has to many technical issues.
